### ISSUE TITLE
Divide polygons with/without cavities into as few convex polygons 

### ISSUE THREAD

**Issue by 13613199288** [LostFan123/pode#27]
Hello，Is it possible to divide polygons with/without cavities into as few convex polygons as possible with your algorithm? What function is used specifically

**Comment by GeorgySk** [comment]
Hello and sorry for taking so long to reply. Somehow I managed to miss the notification. 
Probably, you already do not need the answer but, just for posterity, this algorithm cannot split polygons into as few convex parts as possible. 
The only implementation of such an algorithm that I'm aware of is available in CGAL: [`optimal_convex_partition_2`](https://doc.cgal.org/4.8.2/Partition_2/group__PkgPolygonPartitioning2.html#ga3ca9fb1f363f9f792bfbbeca65ad5cc5). It doesn't support polygons with holes, though.

Also, here are some related repositories that might be of interest:
- https://github.com/ivanfratric/polypartition
- https://github.com/azrafe7/hxGeomAlgo
